### PR TITLE
3.3.0 Compatability

### PR DESCRIPTION
**Pull request by Leinad4Mind**
phpBB removed user_email_hash because after 15 years one user complaint about a silly bug -.-

### CODE REVIEW

**Comment by Galixte** [comment]
Hi @Leinad4Mind could you perform a single PR with https://github.com/ForumHulp/loginwithemail/pull/15 please?

Why two PR? It’s about the same issue in both.

Hi @ForumHulp  could you take a look, please?

**Comment by Leinad4Mind** [comment]
Its 2 PR because I did this on the browser... on a smartphone lol Its fine enough in any case.

**Comment by Galixte** [comment]
You complicate the work to @ForumHulp I’m not sure he’ll be happy.

**Comment by Leinad4Mind** [comment]
Lol instead of 1 click. It's 2 clicks. Any way I don't believe that's a problem.
Forumhulp is certainly busy with other projects, phpbb doesn't seem to be a priority.
Life happens, just be patient.

**Comment by Galixte** [comment]
What did I say last time @Leinad4Mind? Because your PR are splitted @ForumHulp missed to merge your other PR, here: https://github.com/ForumHulp/loginwithemail/pull/15.

Think to merge your work next time, please. ;)

**Pull request merged**
